<?php
/**
 * MoodCast - Çoklu Dil Sistemi
 * Desteklenen: tr, en, ar, fa
 */

$TRANSLATIONS = [

// ─── TÜRKÇE ───────────────────────────────────────────────────────────────────
'tr' => [
    'dir'             => 'ltr',
    'app_name'        => 'MoodCast',
    'tagline'         => 'Havaya Göre Müzik',
    'hero_title_1'    => 'Havanın Ruhunu',
    'hero_title_2'    => 'Müziğe Dönüştür',
    'hero_sub'        => 'Şehrinin hava durumuna göre gerçek şarkılar, tarayıcında çalsın.',
    'search_label'    => 'Şehir Girin',
    'search_ph'       => 'İstanbul, Ankara, New York...',
    'btn_search'      => 'Ara',
    'nav_home'        => 'Ana Sayfa',
    'nav_favorites'   => 'Favorilerim',
    'nav_fav_cities'  => 'Favori Şehirler',
    'btn_login'       => 'Giriş Yap',
    'btn_register'    => 'Kayıt Ol',
    'btn_logout'      => 'Çıkış',
    'genres_title'    => 'Türler',
    'tracks_title'    => 'Şarkılar',
    'tracks_sub'      => 'iTunes 30sn önizleme',
    'loading'         => 'Hava durumu ve şarkılar yükleniyor...',
    'login_title'     => 'Giriş Yap',
    'reg_title'       => 'Kayıt Ol',
    'fav_title'       => 'Favorilerim',
    'fav_cities_title'=> 'Favori Şehirler',
    'forgot_title'    => 'Şifremi Unuttum',
    'forgot_sub'      => 'E-posta adresinize sıfırlama bağlantısı göndereceğiz.',
    'forgot_btn'      => 'Sıfırlama Linki Gönder',
    'label_username'  => 'Kullanıcı Adı',
    'label_email'     => 'E-posta',
    'label_password'  => 'Şifre',
    'label_humidity'  => 'Nem',
    'label_wind'      => 'Rüzgar',
    'label_updated'   => 'Güncellendi',
    'no_favorites'    => 'Henüz favori eklemediniz.',
    'no_fav_cities'   => 'Henüz favori şehir eklemediniz.',
    'add_city'        => 'Şehir Ekle',
    'hint_slash'      => '/ ile hızlı arama',
    'hint_space'      => 'Space ile durdur/devam',
    'demo_account'    => 'Demo',
    'fav_added'       => 'Favorilere eklendi! ♥',
    'fav_removed'     => 'Favorilerden kaldırıldı.',
    'city_added'      => 'Şehir eklendi!',
    'city_removed'    => 'Şehir kaldırıldı.',
    'login_required'  => 'Bu işlem için giriş yapın! 👤',
    'login_success'   => 'Giriş başarılı!',
    'reg_success'     => 'Kayıt başarılı! Giriş yapabilirsiniz.',
    'greeting_morning'=> '🌅 Günaydın!',
    'greeting_noon'   => '☀️ İyi Öğlenler!',
    'greeting_evening'=> '🌆 İyi Akşamlar!',
    'greeting_night'  => '🌙 İyi Geceler!',
    // Çerez banner
    'cookie_text'     => 'Deneyiminizi iyileştirmek için çerezler kullanıyoruz.',
    'cookie_accept'   => 'Kabul Et',
    'cookie_reject'   => 'Reddet',
    'cookie_more'     => 'Daha Fazla',
    // Dark/Light
    'mode_dark'       => 'Karanlık Mod',
    'mode_light'      => 'Aydınlık Mod',
    // Onboarding
    'ob_step1_title'  => 'MoodCast\'e Hoş Geldin! 🎵',
    'ob_step1_text'   => 'Hava durumuna göre müzik öneren akıllı sistemin.',
    'ob_step2_title'  => 'Şehrini Gir 🌍',
    'ob_step2_text'   => 'İstanbul, Paris, Tokyo... Dünyanın herhangi bir şehrini arayabilirsin.',
    'ob_step3_title'  => 'Müziği Keşfet 🎧',
    'ob_step3_text'   => 'Hava durumuna göre özel müzik listeni dinle ve favorine ekle.',
    'ob_btn_next'     => 'İleri',
    'ob_btn_start'    => 'Başla!',
    'ob_btn_skip'     => 'Geç',
],

// ─── İNGİLİZCE ────────────────────────────────────────────────────────────────
'en' => [
    'dir'             => 'ltr',
    'app_name'        => 'MoodCast',
    'tagline'         => 'Music by Weather',
    'hero_title_1'    => 'Turn the Weather',
    'hero_title_2'    => 'Into Music',
    'hero_sub'        => 'Real songs playing in your browser, based on your city\'s weather.',
    'search_label'    => 'Enter City',
    'search_ph'       => 'Istanbul, London, New York...',
    'btn_search'      => 'Search',
    'nav_home'        => 'Home',
    'nav_favorites'   => 'My Favorites',
    'nav_fav_cities'  => 'Favorite Cities',
    'btn_login'       => 'Login',
    'btn_register'    => 'Sign Up',
    'btn_logout'      => 'Logout',
    'genres_title'    => 'Genres',
    'tracks_title'    => 'Songs',
    'tracks_sub'      => 'iTunes 30s preview',
    'loading'         => 'Loading weather and songs...',
    'login_title'     => 'Login',
    'reg_title'       => 'Sign Up',
    'fav_title'       => 'My Favorites',
    'fav_cities_title'=> 'Favorite Cities',
    'forgot_title'    => 'Forgot Password',
    'forgot_sub'      => 'We\'ll send a reset link to your email.',
    'forgot_btn'      => 'Send Reset Link',
    'label_username'  => 'Username',
    'label_email'     => 'Email',
    'label_password'  => 'Password',
    'label_humidity'  => 'Humidity',
    'label_wind'      => 'Wind',
    'label_updated'   => 'Updated',
    'no_favorites'    => 'No favorites yet.',
    'no_fav_cities'   => 'No favorite cities yet.',
    'add_city'        => 'Add City',
    'hint_slash'      => '/ for quick search',
    'hint_space'      => 'Space to play/pause',
    'demo_account'    => 'Demo',
    'fav_added'       => 'Added to favorites! ♥',
    'fav_removed'     => 'Removed from favorites.',
    'city_added'      => 'City added!',
    'city_removed'    => 'City removed.',
    'login_required'  => 'Please login first! 👤',
    'login_success'   => 'Login successful!',
    'reg_success'     => 'Registration successful! You can now login.',
    'greeting_morning'=> '🌅 Good Morning!',
    'greeting_noon'   => '☀️ Good Afternoon!',
    'greeting_evening'=> '🌆 Good Evening!',
    'greeting_night'  => '🌙 Good Night!',
    'cookie_text'     => 'We use cookies to improve your experience.',
    'cookie_accept'   => 'Accept',
    'cookie_reject'   => 'Reject',
    'cookie_more'     => 'Learn More',
    'mode_dark'       => 'Dark Mode',
    'mode_light'      => 'Light Mode',
    'ob_step1_title'  => 'Welcome to MoodCast! 🎵',
    'ob_step1_text'   => 'The smart system that recommends music based on weather.',
    'ob_step2_title'  => 'Enter Your City 🌍',
    'ob_step2_text'   => 'Istanbul, Paris, Tokyo... Search any city in the world.',
    'ob_step3_title'  => 'Discover Music 🎧',
    'ob_step3_text'   => 'Listen to your personalized music list and add favorites.',
    'ob_btn_next'     => 'Next',
    'ob_btn_start'    => 'Get Started!',
    'ob_btn_skip'     => 'Skip',
],

// ─── ARAPÇA ───────────────────────────────────────────────────────────────────
'ar' => [
    'dir'             => 'rtl',
    'app_name'        => 'MoodCast',
    'tagline'         => 'موسيقى حسب الطقس',
    'hero_title_1'    => 'حوّل الطقس',
    'hero_title_2'    => 'إلى موسيقى',
    'hero_sub'        => 'أغانٍ حقيقية تعزف في متصفحك بناءً على طقس مدينتك.',
    'search_label'    => 'أدخل اسم المدينة',
    'search_ph'       => 'إسطنبول، القاهرة، دبي...',
    'btn_search'      => 'بحث',
    'nav_home'        => 'الرئيسية',
    'nav_favorites'   => 'المفضلة',
    'nav_fav_cities'  => 'المدن المفضلة',
    'btn_login'       => 'تسجيل الدخول',
    'btn_register'    => 'إنشاء حساب',
    'btn_logout'      => 'خروج',
    'genres_title'    => 'الأنواع',
    'tracks_title'    => 'الأغاني',
    'tracks_sub'      => 'معاينة 30 ثانية من iTunes',
    'loading'         => 'جارٍ تحميل الطقس والأغاني...',
    'login_title'     => 'تسجيل الدخول',
    'reg_title'       => 'إنشاء حساب',
    'fav_title'       => 'المفضلة',
    'fav_cities_title'=> 'المدن المفضلة',
    'forgot_title'    => 'نسيت كلمة المرور',
    'forgot_sub'      => 'سنرسل رابط إعادة التعيين إلى بريدك الإلكتروني.',
    'forgot_btn'      => 'إرسال رابط الاستعادة',
    'label_username'  => 'اسم المستخدم',
    'label_email'     => 'البريد الإلكتروني',
    'label_password'  => 'كلمة المرور',
    'label_humidity'  => 'الرطوبة',
    'label_wind'      => 'الرياح',
    'label_updated'   => 'تم التحديث',
    'no_favorites'    => 'لا توجد مفضلات بعد.',
    'no_fav_cities'   => 'لا توجد مدن مفضلة بعد.',
    'add_city'        => 'إضافة مدينة',
    'hint_slash'      => '/ للبحث السريع',
    'hint_space'      => 'مسافة للتشغيل/الإيقاف',
    'demo_account'    => 'حساب تجريبي',
    'fav_added'       => 'تمت الإضافة للمفضلة! ♥',
    'fav_removed'     => 'تمت الإزالة من المفضلة.',
    'city_added'      => 'تمت إضافة المدينة!',
    'city_removed'    => 'تمت إزالة المدينة.',
    'login_required'  => 'يرجى تسجيل الدخول أولاً! 👤',
    'login_success'   => 'تم تسجيل الدخول بنجاح!',
    'reg_success'     => 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
    'greeting_morning'=> '🌅 صباح الخير!',
    'greeting_noon'   => '☀️ مساء الخير!',
    'greeting_evening'=> '🌆 مساء النور!',
    'greeting_night'  => '🌙 تصبح على خير!',
    'cookie_text'     => 'نستخدم ملفات تعريف الارتباط لتحسين تجربتك.',
    'cookie_accept'   => 'قبول',
    'cookie_reject'   => 'رفض',
    'cookie_more'     => 'المزيد',
    'mode_dark'       => 'الوضع الداكن',
    'mode_light'      => 'الوضع الفاتح',
    'ob_step1_title'  => 'مرحباً بك في MoodCast! 🎵',
    'ob_step1_text'   => 'النظام الذكي الذي يوصي بالموسيقى بناءً على الطقس.',
    'ob_step2_title'  => 'أدخل مدينتك 🌍',
    'ob_step2_text'   => 'إسطنبول، باريس، طوكيو... ابحث عن أي مدينة في العالم.',
    'ob_step3_title'  => 'اكتشف الموسيقى 🎧',
    'ob_step3_text'   => 'استمع إلى قائمة الموسيقى الخاصة بك وأضف المفضلة.',
    'ob_btn_next'     => 'التالي',
    'ob_btn_start'    => 'ابدأ!',
    'ob_btn_skip'     => 'تخطي',
],

// ─── FARSÇA ───────────────────────────────────────────────────────────────────
'fa' => [
    'dir'             => 'rtl',
    'app_name'        => 'MoodCast',
    'tagline'         => 'موسیقی بر اساس آب‌وهوا',
    'hero_title_1'    => 'آب‌وهوا را به',
    'hero_title_2'    => 'موسیقی تبدیل کن',
    'hero_sub'        => 'آهنگ‌های واقعی در مرورگرت پخش می‌شوند، بر اساس آب‌وهوای شهرت.',
    'search_label'    => 'نام شهر را وارد کنید',
    'search_ph'       => 'تهران، مشهد، استانبول...',
    'btn_search'      => 'جستجو',
    'nav_home'        => 'خانه',
    'nav_favorites'   => 'علاقه‌مندی‌ها',
    'nav_fav_cities'  => 'شهرهای مورد علاقه',
    'btn_login'       => 'ورود',
    'btn_register'    => 'ثبت‌نام',
    'btn_logout'      => 'خروج',
    'genres_title'    => 'ژانرها',
    'tracks_title'    => 'آهنگ‌ها',
    'tracks_sub'      => 'پیش‌نمایش ۳۰ ثانیه‌ای iTunes',
    'loading'         => 'در حال بارگذاری آب‌وهوا و آهنگ‌ها...',
    'login_title'     => 'ورود',
    'reg_title'       => 'ثبت‌نام',
    'fav_title'       => 'علاقه‌مندی‌ها',
    'fav_cities_title'=> 'شهرهای مورد علاقه',
    'forgot_title'    => 'فراموشی رمز عبور',
    'forgot_sub'      => 'لینک بازیابی را به ایمیل شما ارسال می‌کنیم.',
    'forgot_btn'      => 'ارسال لینک بازیابی',
    'label_username'  => 'نام کاربری',
    'label_email'     => 'ایمیل',
    'label_password'  => 'رمز عبور',
    'label_humidity'  => 'رطوبت',
    'label_wind'      => 'باد',
    'label_updated'   => 'به‌روزرسانی',
    'no_favorites'    => 'هنوز علاقه‌مندی ندارید.',
    'no_fav_cities'   => 'هنوز شهر مورد علاقه ندارید.',
    'add_city'        => 'افزودن شهر',
    'hint_slash'      => '/ برای جستجوی سریع',
    'hint_space'      => 'Space برای پخش/توقف',
    'demo_account'    => 'حساب آزمایشی',
    'fav_added'       => 'به علاقه‌مندی‌ها اضافه شد! ♥',
    'fav_removed'     => 'از علاقه‌مندی‌ها حذف شد.',
    'city_added'      => 'شهر اضافه شد!',
    'city_removed'    => 'شهر حذف شد.',
    'login_required'  => 'لطفاً ابتدا وارد شوید! 👤',
    'login_success'   => 'ورود موفقیت‌آمیز بود!',
    'reg_success'     => 'ثبت‌نام موفق بود! اکنون می‌توانید وارد شوید.',
    'greeting_morning'=> '🌅 صبح بخیر!',
    'greeting_noon'   => '☀️ ظهر بخیر!',
    'greeting_evening'=> '🌆 عصر بخیر!',
    'greeting_night'  => '🌙 شب بخیر!',
    'cookie_text'     => 'برای بهبود تجربه شما از کوکی‌ها استفاده می‌کنیم.',
    'cookie_accept'   => 'قبول',
    'cookie_reject'   => 'رد کردن',
    'cookie_more'     => 'بیشتر',
    'mode_dark'       => 'حالت تاریک',
    'mode_light'      => 'حالت روشن',
    'ob_step1_title'  => 'به MoodCast خوش آمدید! 🎵',
    'ob_step1_text'   => 'سیستم هوشمندی که بر اساس آب‌وهوا موسیقی پیشنهاد می‌دهد.',
    'ob_step2_title'  => 'شهرت را وارد کن 🌍',
    'ob_step2_text'   => 'تهران، پاریس، توکیو... هر شهری در جهان را جستجو کن.',
    'ob_step3_title'  => 'موسیقی را کشف کن 🎧',
    'ob_step3_text'   => 'به لیست موسیقی شخصی‌ات گوش بده و مورد علاقه‌هایت را اضافه کن.',
    'ob_btn_next'     => 'بعدی',
    'ob_btn_start'    => 'شروع!',
    'ob_btn_skip'     => 'رد کردن',
],

];

// Aktif dili belirle
function getLang(): string {
    $allowed = ['tr', 'en', 'ar', 'fa'];
    // 1. GET parametresi önce kontrol et (cookie'yi override eder)
    if (!empty($_GET['lang']) && in_array($_GET['lang'], $allowed)) {
        $_COOKIE['mc_lang'] = $_GET['lang'];
        if (!headers_sent()) {
            setcookie('mc_lang', $_GET['lang'], ['expires' => time() + 365*24*3600, 'path' => '/', 'samesite' => 'Strict', 'httponly' => false]);
        }
        return $_GET['lang'];
    }
    // 2. Cookie'den
    if (!empty($_COOKIE['mc_lang']) && in_array($_COOKIE['mc_lang'], $allowed)) {
        return $_COOKIE['mc_lang'];
    }
    // 3. Varsayılan
    return 'tr';
}

function t(string $key): string {
    global $TRANSLATIONS;
    $lang = getLang();
    return $TRANSLATIONS[$lang][$key] ?? $TRANSLATIONS['tr'][$key] ?? $key;
}

function langDir(): string {
    global $TRANSLATIONS;
    $lang = getLang();
    return $TRANSLATIONS[$lang]['dir'] ?? 'ltr';
}
